component_depth: 1
languages:
- csharp
- javascript
exclude:
- .*/knockout-3.4.2.js
- .*/knockout-3.4.2.debug.js
- .*/require.js
- .*/require.min.js
- .*/UnityMvcActivator.cs
- .*/UnityConfig.cs
- /JsJasmineTest\.Tests/Scripts/jasmine/.*
